#! /bin/bash

retval=0

if ! chmod 060 ~/lab0/beldum3 2> /dev/null;  then
	echo "Нет такого файла или каталога ~/lab0/beldum3" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 357 ~/lab0/croagunk1 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 044 ~/lab0/croagunk1/cottonee 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1/cottonee" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 753 ~/lab0/croagunk1/ludicolo 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1/ludicolo" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 577 ~/lab0/croagunk1/butterfree 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1/butterfree" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 305 ~/lab0/croagunk1/pineco 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1/pineco" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 440 ~/lab0/croagunk1/aipom 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/croagunk1/aipom" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 620 ~/lab0/magikarp1 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/magikarp1" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 537 ~/lab0/pidgey7 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 404 ~/lab0/pidgey7/pidgey 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7/pidgey" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 511 ~/lab0/pidgey7/piplup 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7/piplup" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 307 ~/lab0/pidgey7/scolipede 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7/scolipede" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 440 ~/lab0/pidgey7/alakazam 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7/alakazam" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 404 ~/lab0/pidgey7/happiny 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/pidgey7/happiny" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 737 ~/lab0/swellow2 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/swellow2" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 066 ~/lab0/swellow2/hippowdon 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/swellow2/hippowdon" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 335 ~/lab0/swellow2/clefairy 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/swellow2/clefairy" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 500 ~/lab0/swellow2/buizel 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/swellow2/buizel" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 400 ~/lab0/swellow2/sunkern 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/swellow2/sunkern" >&2
	echo "Пропущено" >&2
	retval=1
fi
if ! chmod 640 ~/lab0/taillow8 2> /dev/null; then
	echo "Нет такого файла или каталога ~/lab0/taillow8" >&2
	echo "Пропущено" >&2
	retval=1
fi

exit ${retval}
